### PR TITLE
Updated Fx manifest and change for opening inventories

### PR DESCRIPTION
**Pull request by FBFezz**

### CODE REVIEW

**Comment by FBFezz** [comment]
Little update to readme to give info on how to get access to openinv command

**Comment by RuisSoftware** [comment]
Can you make it so people can choose in config if they want to disable it? Thanks.

**Comment by FBFezz** [comment]
Sorry, I didn't get a notification for some reason but should be right now? Code is a little sloppy but It should work

**Comment by RuisSoftware** [comment]
Amazing thank you!

**Pull request merged**
