### PR TITLE
Preperations for NPCPlanes rewrite

### PR DESCRIPTION
**Pull request by Bluscream**

### CODE REVIEW

**Comment by RuisSoftware** [comment]
Hi! Thanks for your work, but i cannot test it rn. Is it ready for a merge?

**Comment by Bluscream** [comment]
> Hi! Thanks for your work, but i cannot test it rn. Is it ready for a merge?

Nope, thats why its still a draft. The basic concept is there but theres a lot of tuning to do. I really underestimated how complicated this thing will become once making it dynamic. I wish someone that didnt start 2 weeks ago with fivem could help me with it ^^

**Comment by Bluscream** [comment]
Especially the stuff with multiple waypoints along the way with zones is really hard to do dynamically. I have a unpushed branch where i am basically just tryjng to get one flight to work at all without infinite circles over the destination or crashing into trees on before even lifting off

**Comment by boermansjo** [comment]
Are you still working on this ?
It looks very nice. And with time, I can look into it and help if possible.

**Comment by Bluscream** [comment]
Sadly i'm no longer in the FiveM community so i wontbe of much help.
However you're free to take what i already did and finish it, it was a lot of work done already ^^

**Comment by Bluscream** [comment]
I will gladly answer questions about parts of the changes and translations if someone decides to work on this and doesnt understand something though.

**Pull request merged**
